spring.application.name=projet

# Desactive le lancement automatique du job au demarrage
spring.batch.job.enabled=false

# Initialise automatiquement le schema de metadonnees Spring Batch
spring.batch.jdbc.initialize-schema=always
spring.sql.init.mode=always

#### VEUILLEZ COMMENTER LA BASE QUI N'EST PAS UTILISE ###

# -------------------------
# SQLite
# -------------------------
#spring.datasource.url=jdbc:sqlite:adresse.db
#spring.datasource.driver-class-name=org.sqlite.JDBC
#spring.sql.init.schema-locations=classpath:schema_sqlite.sql


# -------------------------
# POSTGRES
# -------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/adresse
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.schema-locations=classpath:schema_postgres.sql
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

##########################################################
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.devtools.restart.enabled=false
logging.level.org.springframework.batch=DEBUG


